POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "admin"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer asd.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYzA1NzlmZmZmZjU1YTI3MzM2ZGE5ZiIsImlhdCI6MTY1Njc3OTUyMywiZXhwIjoxNjU2NzgzMTIzfQ.wdeTLwXunn70ibA6yZ90ZLrTdxuJjFAb7Vz4ii4X0so

{
    "title": "Test2",
    "author": "Test Author 2",
    "url": "http://test.com",
    "likes": 5
}

###

DELETE http://localhost:3003/api/blogs/62c07c67d2029479a9255bbc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYzA1NzlmZmZmZjU1YTI3MzM2ZGE5ZiIsImlhdCI6MTY1Njc3OTUyMywiZXhwIjoxNjU2NzgzMTIzfQ.wdeTLwXunn70ibA6yZ90ZLrTdxuJjFAb7Vz4ii4X0so

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "none",
    "password": "admin"
}